### ISSUE TITLE
severe tps issues

### ISSUE THREAD

**Issue by Lewisking50** [baguchan/EnchantWithMob#3]
The enchantments seem to cause severe tps issues to the point of unplayability.
I enchanted an Overworld Drake from Wyrmroost and Skeleton Warriors from Greek Fantasy and some time later (it wasn't immediate) everything started lagging.
I gave all of them Protection 4, Strength 3 and Speed 2.

MC version: 1.16.4
Forge: forge-1.16.4-35.1.37
Modpack: Mineshafts & Monsters v1.2.2

**Comment by Nubidubi23** [comment]
It wasn't immediate for me either

**Comment by baguchan** [comment]
Have you tried this version?(this version supported 1.16.4 and 1.16.5)
Fixed a bug where NBT tags were amplified
https://www.curseforge.com/minecraft/mc-mods/enchant-with-mob/files/3278813
